apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containo-orders-frontend
  namespace: containo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: containo
        microservice: orders
        service: api
        type: platform
    spec:
      containers:
        - name: containo-orders-api
          image: tomkerkhove/containo.services.orders.api:0.1.31
          ports:
          - containerPort: 80
          env:
          - name:  ASPNETCORE_ENVIRONMENT
            value: Development
          - name:  ASPNETCORE_URLS
            value: http://+:80
          - name:  Orders_Queue_Name
            value: orders-kubernetes
          - name: Services_Validation_Url
            value: http://localhost:81
          - name:  Redis_ConnectionString
            value: containo-orders-cache-service:6666
          - name:  ServiceBus_ConnectionString
            valueFrom:
              secretKeyRef:
                name: containo-orders
                key: ServiceBus_ConnectionString
          - name:  TableStorage_ConnectionString
            valueFrom:
              secretKeyRef:
                name: containo-orders
                key: TableStorage_ConnectionString
        - name: containo-orders-api-validator
          image: tomkerkhove/containo.services.orders.validator:0.1.31
          ports:
          - containerPort: 81
          env:
          - name:  ASPNETCORE_ENVIRONMENT
            value: Development
          - name:  ASPNETCORE_URLS
            value: http://+:81
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containo-orders-cache
  namespace: containo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: containo
        microservice: orders
        service: cache
        type: infrastructure
    spec:
      containers:
        - name: containo-orders-cache
          image: redis:4.0.11
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containo-orders-queue-processor
  namespace: containo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: containo
        microservice: orders
        service: queue-processor
        type: platform
    spec:
      containers:
        - name: containo-orders-queueprocessor
          image: tomkerkhove/containo.services.orders.queueprocessor:0.1.31
          env:
          - name:  ASPNETCORE_ENVIRONMENT
            value: Development
          - name:  ASPNETCORE_URLS
            value: http://+:81
          - name:  Orders_Queue_Name
            value: orders-kubernetes
          - name:  ServiceBus_ConnectionString
            valueFrom:
              secretKeyRef:
                name: containo-orders
                key: ServiceBus_ConnectionString
          - name:  TableStorage_ConnectionString
            valueFrom:
              secretKeyRef:
                name: containo-orders
                key: TableStorage_ConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: containo-orders-cache-service
  namespace: containo
  labels:
    app: containo
    microservice: orders
    service: cache
    type: infrastructure
spec:
  selector:
    app: containo
    microservice: orders
    service: cache
    type: infrastructure
  ports:
  - protocol: TCP
    port: 6666
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: containo-orders-frontend
  namespace: containo
  labels:
    app: containo
    microservice: orders
    service: api
    type: infrastructure
spec:
  type: LoadBalancer
  selector:
    app: containo
    microservice: orders
    service: api
  ports:
  - protocol: TCP
    port: 1337
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: containo-orders
  namespace: containo
type: Opaque
data:
  ServiceBus_ConnectionString: RW5kcG9pbnQ9c2I6Ly9jb250YWluby5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPUNvbnRhaW5lcnM7U2hhcmVkQWNjZXNzS2V5PThLNlhRVnJxbk1ZcXlwNGdCdmRYOTJRS21YM2JQUStLS2NGekFxaTkyR009
  TableStorage_ConnectionString: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWNvbnRhaW5vO0FjY291bnRLZXk9aHYwRlZtRFQrNDNGcnlEODlXZmt5Q0NxK3JnamhtZEFKZHpQekpMb1NaTEhNaGFBc2VaeDR3aVJCS2w0dTJPZlY1R0lOSWpxQVE3S00ycjV5ODUxdHc9PTtCbG9iRW5kcG9pbnQ9aHR0cHM6Ly9jb250YWluby5ibG9iLmNvcmUud2luZG93cy5uZXQvO1F1ZXVlRW5kcG9pbnQ9aHR0cHM6Ly9jb250YWluby5xdWV1ZS5jb3JlLndpbmRvd3MubmV0LztUYWJsZUVuZHBvaW50PWh0dHBzOi8vY29udGFpbm8udGFibGUuY29yZS53aW5kb3dzLm5ldC87RmlsZUVuZHBvaW50PWh0dHBzOi8vY29udGFpbm8uZmlsZS5jb3JlLndpbmRvd3MubmV0Lzs=
---
apiVersion: v1
kind: Namespace
metadata:
  name: containo
